### ISSUE TITLE
出现了CUDA out of memory

### ISSUE THREAD

**Issue by hcfeng201** [YangYang/speech_enhancement_phase_and_harmonics_aware#1]
你好，
      我用的是论文里提到的voice bank数据集进行训练和验证，沿用你设置的默认参数，但在迭代过程中还是出现了内存溢出（如下图），请问可以指点一下优化的方向吗？
      另外训练过程中运行top可以看到单个进程申请的内存有点大（350GB），实际常驻内存不到2G，这是否会有不利的影响。
![image](https://user-images.githubusercontent.com/34930362/71498183-49685080-2896-11ea-9347-85a9a701af66.png)

**Comment by YangYang** [comment]
应该是网络比较大，我是22G跑满的……
你可以尝试改小batch

**Comment by YangYang** [comment]
对于虚拟内存占用情况我以前倒是没有考虑到，我也不太清楚会不会有问题

**Comment by hcfeng201** [comment]
> 对于虚拟内存占用情况我以前倒是没有考虑到，我也不太清楚会不会有问题

感谢指点，我把batch减半改成2试试。

**Comment by YangYang** [comment]
不客气的～
